### ISSUE TITLE
Add login page to the PWA

### ISSUE THREAD

**Issue by progmatic-99** [progmatic-99/SmartPark#1]
Add the login page for the user that verifies the user by sending an OTP to the user's phone.

**Comment by progmatic-99** [comment]
We should add **Login with Google** to the _login page_ as most users would have a google account. So, the login process becomes easier with one click.
For that, we have to add _Google Oauth_

**Comment by chaudharypraveen98** [comment]
Added a geneeral login at localhost/login/

**Comment by progmatic-99** [comment]
I was thinking of adding *Google OAuth* instead of django login
